import { ActivityCategory } from './activity';
import { GoalStatus } from './goal';

export const ErrorCodes = {
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  RBAC_ROLE_DENIED: 'RBAC_ROLE_DENIED',
  USER_EMAIL_DUPLICATE: 'USER_EMAIL_DUPLICATE',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_PASSWORD_INVALID: 'USER_PASSWORD_INVALID',
  ACTIVITY_CATEGORY_INVALID: `ACTIVITY_CATEGORY_INVALID:${Object.values(ActivityCategory).join('|')}`,
  ACTIVITY_NOT_FOUND: 'ACTIVITY_NOT_FOUND',
  FACTOR_NOT_FOUND: 'FACTOR_NOT_FOUND',
  GOAL_STATUS_INVALID: `GOAL_STATUS_INVALID:${Object.values(GoalStatus).join('|')}`,
  GOAL_NOT_FOUND: 'GOAL_NOT_FOUND',
  AUDIT_LOG_FAILED: 'AUDIT_LOG_FAILED',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  DATABASE_FAILED: 'DATABASE_FAILED'
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

